# Generated by Django 4.0.2 on 2022-04-19 03:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonatePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.StreamField([('description', wagtail.core.blocks.RichTextBlock())], default='')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 3, 58, 32, 733053, tzinfo=utc))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 3, 58, 32, 733065, tzinfo=utc))),
                ('hero_image', models.ForeignKey(blank=True, help_text='2400X858px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DonateIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_heading', models.CharField(blank=True, help_text='40 character limit.', max_length=140, null=True)),
                ('hero_caption', models.CharField(blank=True, help_text='140 character limit.', max_length=140, null=True)),
                ('hero_image', models.ForeignKey(blank=True, help_text='2400X858px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
