# Generated by Django 5.0.6 on 2024-06-30 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donate', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateindexpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='2400X858px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='hero_image',
            field=models.ForeignKey(help_text='2400X858px', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='images.customimage'),
        ),
    ]
