# Generated by Django 4.0.2 on 2022-04-19 05:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_alter_donateindexpage_hero_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatepage',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 5, 8, 6, 480855, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='donatepage',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 5, 8, 6, 480842, tzinfo=utc)),
        ),
    ]
