# Generated by Django 4.0.2 on 2022-04-19 05:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('donate', '0006_alter_donatepage_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateindexpage',
            name='hero_image',
            field=models.ForeignKey(default='', help_text='2400X858px', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='images.customimage'),
        ),
        migrations.AlterField(
            model_name='donatepage',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 5, 10, 15, 176681, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='donatepage',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 5, 10, 15, 176670, tzinfo=utc)),
        ),
    ]
