# Generated by Django 4.0.2 on 2022-04-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0008_alter_donateindexpage_hero_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatepage',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='donatepage',
            name='start_time',
        ),
    ]
