# Generated by Django 4.0.2 on 2022-04-13 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('page', '0002_standardpage_hero_caption_standardpage_hero_cta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='2400X858px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
    ]
