apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-masjid-app
  labels:
    app: masjid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: masjid
  template:
    metadata:
      labels:
        app: masjid
    spec:
      initContainers:
        - name: migrate
          image: ghcr.io/fourfridays/masjid:dev
          imagePullPolicy: Always
          command: ["python", "manage.py", "migrate"]
          envFrom:
          - secretRef:
              name: secret
      containers:
        - image: ghcr.io/fourfridays/masjid:dev
          name: masjid
          envFrom:
          - secretRef:
              name: secret
          - configMapRef:
              name: config
          ports:
            - containerPort: 8080
              name: gunicorn