# Generated by Django 4.0.2 on 2022-04-18 06:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventpage_body_eventpage_end_time_eventpage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 6, 42, 57, 252587, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 6, 42, 57, 252576, tzinfo=utc)),
        ),
    ]
