# Generated by Django 4.0.2 on 2022-04-18 06:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_eventpage_end_time_alter_eventpage_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 6, 44, 23, 712138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 6, 44, 23, 712126, tzinfo=utc)),
        ),
    ]
