# Generated by Django 4.0.2 on 2022-04-18 07:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventindexpage_hero_image_alter_eventpage_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventindexpage',
            name='hero_caption',
            field=models.CharField(blank=True, help_text='140 character limit.', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='eventindexpage',
            name='hero_heading',
            field=models.CharField(blank=True, help_text='40 character limit.', max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 7, 25, 37, 366375, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 7, 25, 37, 366357, tzinfo=utc)),
        ),
    ]
