# Generated by Django 4.0.2 on 2022-04-18 08:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventindexpage_hero_caption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpage',
            old_name='image',
            new_name='hero_image',
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 8, 6, 9, 48209, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 8, 6, 9, 48196, tzinfo=utc)),
        ),
    ]
