# Generated by Django 4.0.2 on 2022-04-18 21:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_rename_image_eventpage_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 21, 7, 6, 600083, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 21, 7, 6, 600071, tzinfo=utc)),
        ),
    ]
