# Generated by Django 4.0.2 on 2022-04-19 06:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_eventpage_end_time_alter_eventpage_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 6, 7, 2, 103672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 6, 7, 2, 103659, tzinfo=utc)),
        ),
    ]
