# Generated by Django 4.0.2 on 2022-04-21 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_eventpage_end_time_alter_eventpage_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 9, 34, 14, 834751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 9, 34, 14, 834740, tzinfo=utc)),
        ),
    ]
