# Generated by Django 5.0.6 on 2024-06-30 01:37

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorter', models.CharField(blank=True, default='', max_length=1, null=True)),
                ('title', models.CharField(max_length=7, unique=True)),
                ('adhan', models.DateTimeField(blank=True, help_text='Any changes to adhan time will be overwritten by the API', null=True)),
                ('salah', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerScheduleAPISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5)),
                ('country', models.CharField(help_text='Two letter abbreviation for county. Country Code. Ex: US, MX, ES, etc.', max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('time_format', models.IntegerField(default=0, help_text='0: 24hr; 1: 12hr; 2: 12hr without suffix; 3: floating')),
                ('time_zone', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerScheduleExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='120 max characters', max_length=120)),
                ('text', wagtail.fields.StreamField([('description', wagtail.blocks.RichTextBlock())], default='')),
            ],
        ),
    ]
