# Generated by Django 4.0.2 on 2022-04-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_schedule', '0002_alter_prayer_azan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='salah',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
