# Generated by Django 4.0.2 on 2022-04-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_schedule', '0004_rename_azan_prayer_adhan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='adhan',
            field=models.DateTimeField(blank=True, help_text='Any changes to adhan time will be overwritten by the API', null=True),
        ),
    ]
