# Generated by Django 4.0.2 on 2022-04-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_schedule', '0005_alter_prayer_adhan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerScheduleAPISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5)),
                ('country', models.CharField(help_text='Two letter abbreviation for county. Country Code. Ex: US, MX, ES, etc.', max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('time_format', models.IntegerField(default=0, help_text='0: 24hr; 1: 12hr; 2: 12hr without suffix; 3: floating')),
                ('time_zone', models.CharField(max_length=120)),
            ],
        ),
    ]
