# Generated by Django 4.0.2 on 2022-04-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_schedule', '0007_prayerscheduleextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerscheduleextra',
            name='title',
            field=models.CharField(default='', help_text='120 max characters', max_length=120),
        ),
    ]
